### ISSUE TITLE
Create a links plan?

### ISSUE THREAD

**Issue by IldeNet** [Heistergand/fanfields2#62]
I wanted to take a moment to express my sincere gratitude for the outstanding work you've done as a programmer. 
Your coding skills and attention to detail have not only brought our project to life but have also elevated it to a level we hadn't imagined. I speak on behalf of the entire team when I say that your contributions have been invaluable. Your commitment to excellence has not only met but exceeded our expectations.
I would like to ask you if it is possible to implement the option of drawing up a plan for a person, which tells the portal what to go to and the links that must be made from each portal. All of this can be exported in plain text to make the work easier.
I have tried exporting the portals to ingress-maxfield but it completely changes the strategy shown with your tool.
Once again, thank you for your remarkable work.

**Comment by Heistergand** [comment]
> I wanted to take a moment to express my sincere gratitude for the outstanding work you've done as a programmer.
> Your coding skills and attention to detail have not only brought our project to life but have also elevated it to a level we hadn't imagined. I speak on behalf of the entire team when I say that your contributions have been invaluable. Your commitment to excellence has not only met but exceeded our expectations.

...seriously? A business bs generator? 🤣
I think my code is quite severe spaghetti, but don't tell anyone.

> I would like to ask you if it is possible to implement the option of drawing up a plan for a person, which tells the portal what to go to and the links that must be made from each portal. All of this can be exported in plain text to make the work easier.
> I have tried exporting the portals to ingress-maxfield but it completely changes the strategy shown with your tool.

You can just use the "Show as list" function and walk the portals in that order. At each portal, link back to the previous portals in ascending plan order.

**Comment by Heistergand** [comment]
Kind of implemented in #67 
You can now see all link actions that have to be done in the "Show As List" dialog.
