### ISSUE TITLE
Current version is broken on IITC Mobile

### ISSUE THREAD

**Issue by Augustronic** [Heistergand/fanfields2#64]
Hi!
Is the actual mobile version meant to run on Android?
It's not even showing up in my list of loaded plugins in "About IITC".
Cheers, 
Augustronic

**Comment by ReVanTis** [comment]
I'm also having trouble running it on the latest IITC Mobile Beta, debug console shows:
```
<user-plugin/storage/emulated/0/IITC_Mobile/plugins/iitc_plugin_fanfields2.user.js>:683: Uncaught TypeError: window.pluginCreateHook is not a function
```
Seems a78402270bac0559bae70d81ac0a95722e33dcb1 introduces a regression on mobile.
I manually reverted it locally and it runs but without the book mark only feature.

**Comment by Augustronic** [comment]
> I'm also having trouble running it on the latest IITC Mobile Beta, debug console shows:
> 
> ```
> <user-plugin/storage/emulated/0/IITC_Mobile/plugins/iitc_plugin_fanfields2.user.js>:683: Uncaught TypeError: window.pluginCreateHook is not a function
> ```
> 
> Seems [a784022](https://github.com/Heistergand/fanfields2/commit/a78402270bac0559bae70d81ac0a95722e33dcb1) introduces a regression on mobile. I manually reverted it locally and it runs but without the book mark only feature.

You reverted the code changes or is there a versions repository?

**Comment by ReVanTis** [comment]
> > I'm also having trouble running it on the latest IITC Mobile Beta, debug console shows:
> > ```
> > <user-plugin/storage/emulated/0/IITC_Mobile/plugins/iitc_plugin_fanfields2.user.js>:683: Uncaught TypeError: window.pluginCreateHook is not a function
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Seems [a784022](https://github.com/Heistergand/fanfields2/commit/a78402270bac0559bae70d81ac0a95722e33dcb1) introduces a regression on mobile. I manually reverted it locally and it runs but without the book mark only feature.
> 
> You reverted the code changes or is there a versions repository?

I did it locally but you can try using this link for the version that before merging a78402270bac0559bae70d81ac0a95722e33dcb1:
Raw file link is here:
https://github.com/Heistergand/fanfields2/raw/19661ea3e5dff9659f7beecac9989ae68881dab9/iitc_plugin_fanfields2.user.js

from:
https://github.com/Heistergand/fanfields2/blob/19661ea3e5dff9659f7beecac9989ae68881dab9/iitc_plugin_fanfields2.user.js

**Comment by Augustronic** [comment]
> > > I'm also having trouble running it on the latest IITC Mobile Beta, debug console shows:
> > > ```
> > > <user-plugin/storage/emulated/0/IITC_Mobile/plugins/iitc_plugin_fanfields2.user.js>:683: Uncaught TypeError: window.pluginCreateHook is not a function
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Seems [a784022](https://github.com/Heistergand/fanfields2/commit/a78402270bac0559bae70d81ac0a95722e33dcb1) introduces a regression on mobile. I manually reverted it locally and it runs but without the book mark only feature.
> > 
> > 
> > You reverted the code changes or is there a versions repository?
> 
> I did it locally but you can try using this link for the version that before merging [a784022](https://github.com/Heistergand/fanfields2/commit/a78402270bac0559bae70d81ac0a95722e33dcb1): Raw file link is here: https://github.com/Heistergand/fanfields2/raw/19661ea3e5dff9659f7beecac9989ae68881dab9/iitc_plugin_fanfields2.user.js
> 
> from: https://github.com/Heistergand/fanfields2/blob/19661ea3e5dff9659f7beecac9989ae68881dab9/iitc_plugin_fanfields2.user.js

Excellent!
Thank you for the easy way!

**Comment by Heistergand** [comment]
I'll check on this.

**Comment by Penumbruh** [comment]
Glad to see this is being worked on. I was able to get it to work on iOS and Chrome for Mac but I thought I was doing something wrong because I couldn't get it to come up on my Android phone.

**Comment by Heistergand** [comment]
Although I think I've fixed this and closed the issue, please update your IITC Plugins and test it. I welcome every feedback.

**Comment by Penumbruh** [comment]
The plugin is working fine on my Nothing Phone (2) now. Thank you for
fixing this! 🤝

**Comment by Augustronic** [comment]
It's working fine on my Samsung SS22 Android!
Thank you very much!
