### ISSUE TITLE
Easier Google Maps navigation

### ISSUE THREAD

**Issue by PacoBell** [Heistergand/fanfields2#69]
I'm planning an op with hundreds of stops. Google Maps doesn't like that many stops. On PC, the UI overflows the page and on mobile it gets truncated to 3 stops. I would like it so that when you expand each captured portal that the "link to" portal name is a GMaps URL directly to that latlong destination. Or maybe just link to the info page for that portal as "Map links" already exists there? Thanks for your consideration.

...nice.

**Comment by Heistergand** [comment]
I'm not quite sure why you would need the nav link for a "link to" portal when standing on a just captures portal linking back to where you've already been. 

But I understand the need of a clean portal navigation list.

**Comment by PacoBell** [comment]
Point taken about "link to". Perhaps what I meant to say was that each portal should have a Gmaps link somewhere. Looking at the UI, that Action:Capture text looks like an ideal location to embed those links. It seems like a nice way to make that verb actionable.
